apiVersion: v1
kind: Pod
metadata:
  name: ceph-mount-test
spec:
  nodeSelector:
    cephtest: "true"
  containers:
  - name: cephfs-rw
    image: nginx
    volumeMounts:
    - mountPath: "/mnt/cephfs"
      name: cephfs
  volumes:
  - name: cephfs
    cephfs:
      monitors:
#This only works if you have skyDNS resolveable from the kubernetes node. Otherwise you must manually put in a mon-ip.
      - ceph-mon.ceph:6789
      user: admin
      secretRef:
        name: ceph-client-key
