---
kind: ReplicationController
apiVersion: v1
metadata:
  labels:
    app: ceph
    daemon: mon
  name: ceph-mon
  namespace: ceph
spec:
  replicas: 2
  selector:
    app: ceph
    daemon: mon
  template:
    metadata:
      name: ceph-mon
      namespace: ceph
      labels:
        app: ceph
        daemon: mon
    spec:
      volumes:
        - name: ceph-dir
          hostPath:
            path: /opt/ceph
        - name: ceph-conf
          secret:
            secretName: ceph-conf-combined
        - name: ceph-bootstrap-osd-keyring
          secret:
            secretName: ceph-bootstrap-osd-keyring
        - name: ceph-bootstrap-mds-keyring
          secret:
            secretName: ceph-bootstrap-mds-keyring
        - name: ceph-bootstrap-rgw-keyring
          secret:
            secretName: ceph-bootstrap-rgw-keyring
      containers:
        - name: ceph-mon
          image: quay.io/acaleph/ceph-base:kubernetes
          # imagePullPolicy: Always
          # command: ["sleep","10000"]
          serviceAccount: default
          ports:
            - containerPort: 6789
          env:
            - name: CEPH_DAEMON
              value: MON
            - name: CEPH_PUBLIC_NETWORK
              value: 10.2.0.0/16
            - name: CEPH_CLUSTER_NETWORK
              value: 10.2.0.0/16
            - name: KV_TYPE
              value: k8s
          volumeMounts:
            - name: ceph-dir
              mountPath: /opt/ceph
              
            - name: ceph-conf
              mountPath: /etc/ceph
            - name: ceph-bootstrap-osd-keyring
              mountPath: /var/lib/ceph/bootstrap-osd
            - name: ceph-bootstrap-mds-keyring
              mountPath: /var/lib/ceph/bootstrap-mds
            - name: ceph-bootstrap-rgw-keyring
              mountPath: /var/lib/ceph/bootstrap-rgw

